name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
branding:
  icon: search
  color: green
inputs:
  githubEnvOnly:
    description: 'Show environment variable only starts with GITHUB'
    default: 'true'
    required: false  
runs:
  using: 'node16'
  main: 'dist/index.js'